# Site settings
title: Graphic Biotech
email: #
description: >
  Innovation - Design - Biology - Policy
baseurl:  # the subpath of your site, e.g. /blog/
url:  kenza.science
twitter_username: @kenzasam
github_username: #

# Build settings
markdown: kramdown

highlighter: pygments

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  projects:
    output: true
    permalink: /projects/:path/
  blog:
    output: true
    permalink: /blog:path/
